lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# theme variables
remote-theme: pages-themes/minimal@v0.2.0

# jekyll plugins
plugins:
- jekyll-remote-theme

# site variables
title: Peter Reyntjens
description: Personal blog of Peter Reyntjens (work in progress)
